//! Config-ops / dashboard round-trip guarantee for the discovery writer
//! (TNS-onboarding bead `.12`; design spec §C/§E,
//! `docs/tns-discovery-onboarding.md`).
//!
//! `oraclemcp setup --discover` writes THROUGH [`ConfigOpsService`] — the same
//! backend the dashboard/operator endpoints (`/operator/v1/config/*`) drive. This
//! test locks the contract that the generated annotated config round-trips
//! through that backend unchanged: stage → apply yields a valid outcome, `status`
//! enumerates exactly the generated profiles, a no-op re-apply of the same bytes
//! is stable, the empty→generated reload plan is computed without error, and no
//! secret material appears in any preview, status, or diff (mirrors the leakage
//! assertions in `config_ops.rs`).

use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

use oraclemcp_config::discovery::render_annotated_config;
use oraclemcp_config::discovery::synth::{
    DiscoveredNetService, DiscoverySynthesis, SynthOptions, synthesize_profiles,
};
use oraclemcp_core::config_ops::{ConfigOpsBackend, ConfigOpsService};
use oraclemcp_core::file_store::FileStore;

fn unique_temp_dir(label: &str) -> PathBuf {
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock after epoch")
        .as_nanos();
    let dir = std::env::temp_dir().join(format!(
        "oraclemcp-discover-roundtrip-{}-{stamp}-{label}",
        std::process::id()
    ));
    std::fs::create_dir_all(&dir).expect("create temp dir");
    dir
}

/// A two-net-service synthesis whose connect strings are EZConnect (host/port),
/// so the hosts, credential refs, and wallet path are distinct leakage canaries
/// that must never surface in a redacted preview/status/diff.
fn golden_synth() -> DiscoverySynthesis {
    let mut sales = DiscoveredNetService::new("SALES_RO");
    sales.host = Some("sales.internal.example.com".to_owned());
    sales.port = Some(1521);
    sales.service_name = Some("SALESSVC".to_owned());

    let mut tcps = DiscoveredNetService::new("PRIMARY_TCPS");
    tcps.protocol = Some("TCPS".to_owned());
    tcps.host = Some("tcps.internal.example.com".to_owned());
    tcps.port = Some(2484);
    tcps.service_name = Some("PRIMARYSVC".to_owned());
    tcps.wallet_location = Some("/etc/oracle/wallet/primary".to_owned());

    synthesize_profiles(
        &[sales, tcps],
        &SynthOptions {
            tns_admin_reachable: false,
        },
    )
}

/// Canary strings that live only in the raw config and must never appear on a
/// redacted surface (connect-string hosts, credential/wallet secret refs, wallet
/// path).
const CANARIES: &[&str] = &[
    "sales.internal.example.com",
    "tcps.internal.example.com",
    "env:ORACLE_SALES_RO_PASSWORD",
    "env:ORACLE_PRIMARY_TCPS_PASSWORD",
    "env:ORACLE_PRIMARY_TCPS_WALLET_PASSWORD",
    "/etc/oracle/wallet/primary",
];

fn assert_no_canary(surface: &str, where_: &str) {
    for canary in CANARIES {
        assert!(
            !surface.contains(canary),
            "redacted {where_} leaked {canary}: {surface}"
        );
    }
}

#[test]
fn generated_config_round_trips_through_config_ops_without_leaking_secrets() {
    let synth = golden_synth();
    let rendered = render_annotated_config(&synth);

    let store_root = unique_temp_dir("store");
    let backend = ConfigOpsBackend::new(FileStore::open(&store_root).expect("open file store"));
    let target_dir = unique_temp_dir("target");
    let target = target_dir.join("profiles.toml");

    let service = ConfigOpsService::new(backend, target.clone(), None);

    // stage: the empty→generated reload plan is computed without error, and the
    // redacted preview leaks no secret material.
    let preview = service.stage(&rendered).expect("stage generated config");
    assert!(
        !preview.original_existed,
        "the target did not pre-exist (fresh discovery)"
    );
    // The reload plan between the empty current and the generated draft exists.
    let _reload_plan = &preview.reload_plan;
    let preview_json = serde_json::to_string(&preview).expect("preview json");
    assert_no_canary(&preview_json, "preview");

    // apply: a valid outcome with a backup + verified installed bytes.
    let outcome = service
        .apply(&rendered, Some(&preview.current_sha256))
        .expect("apply generated config");
    assert!(outcome.apply.backup_path.exists(), "a backup was written");
    let installed = std::fs::read_to_string(&target).expect("installed config");
    assert_eq!(
        installed, rendered,
        "config-ops installs the generated bytes verbatim (comments preserved)"
    );

    // status: enumerates EXACTLY the generated profiles, redacted, no leakage.
    let status = service.status().expect("status");
    let mut names: Vec<&str> = status.profiles.iter().map(|p| p.name.as_str()).collect();
    names.sort_unstable();
    assert_eq!(
        names,
        vec!["primary_tcps", "sales_ro"],
        "status enumerates exactly the generated profiles"
    );
    for profile in &status.profiles {
        assert_eq!(
            profile.max_level,
            oraclemcp_config::OperatingLevel::ReadOnly,
            "every generated profile is READ_ONLY-capped"
        );
    }
    let status_json = serde_json::to_string(&status).expect("status json");
    assert_no_canary(&status_json, "status");

    // A subsequent no-op re-apply of the same bytes is stable.
    let current_sha = oraclemcp_audit::sha256_hex(installed.as_bytes());
    let reapply = service
        .apply(&rendered, Some(&current_sha))
        .expect("no-op re-apply of the same bytes");
    assert_eq!(
        std::fs::read_to_string(&target).expect("re-read"),
        rendered,
        "the installed config is stable across an identical re-apply"
    );
    assert!(reapply.apply.backup_path.exists());

    std::fs::remove_dir_all(&store_root).ok();
    std::fs::remove_dir_all(&target_dir).ok();
}
