//! The annotated safe-config writer (TNS-onboarding beads `.7`, `.8`; design
//! spec §C, `docs/tns-discovery-onboarding.md`).
//!
//! Renders a discovery [`DiscoverySynthesis`] into a self-documenting
//! `profiles.toml`: a **bootable minimum** (the keys required for a valid,
//! governed, least-privilege profile — read-only by default) plus a
//! **self-documenting commented menu** (every remaining optional key present but
//! commented, each with a one-line help string using its exact serde name, so
//! uncommenting yields a valid key).
//!
//! The output round-trips through [`crate::OracleMcpConfig::from_toml_str`] —
//! both `OracleMcpConfig` and [`crate::ConnectionProfile`] are
//! `#[serde(deny_unknown_fields)]`, so every uncommented key MUST be a real
//! serde field and no unknown key may ever appear.
//!
//! # Read-only-safe posture (bead `.7`)
//!
//! Every synthesized profile is capped at `READ_ONLY` on both `max_level` and
//! `default_level`, and those levels are written **explicitly** (never left to a
//! struct default) so the safety ceiling is legible in the file. The writer also
//! emits, once near the top, a [`read_only_safety_comment`] block carrying the
//! least-privilege database-account guidance and the audit-before-escalation
//! safety note. Discovery never marks a profile `protected` or raises a level;
//! an unverified profile stays `READ_ONLY` and is flagged needs-verification.

use crate::discovery::synth::{DiscoverySynthesis, SynthesizedProfile};

/// The commented, governed/least-privilege safety block the writer emits once
/// near the top of the file (bead `.7`). It states the read-only-by-default
/// posture, the least-privilege database-account guidance, and the
/// audit-before-escalation safety note.
///
/// Every line is already a `#` TOML comment, so the block can be embedded
/// verbatim and the file still parses.
#[must_use]
pub fn read_only_safety_comment() -> String {
    // Framing note: governed, least-privilege / read-only by default — NOT
    // "safe-by-default". Keep this wording aligned with the honesty-grep gate.
    let lines = [
        "# ── Governed, least-privilege posture (read-only by default) ──────────────",
        "# Discovery writes every profile capped at READ_ONLY on BOTH max_level and",
        "# default_level, set explicitly so the ceiling is legible here and never",
        "# relies on a default. A profile is not marked protected and no level is",
        "# raised on your behalf.",
        "#",
        "# Least-privilege account: point credential_ref at a DEDICATED Oracle",
        "# account granted only CONNECT and SELECT — never an application-owner or",
        "# SYSDBA/SYSTEM login. The password lives only in the environment variable",
        "# the discovery report names; it is never written to this file.",
        "#",
        "# Before you raise any profile's max_level above READ_ONLY, deliberately",
        "# edit that max_level AND configure [audit].key_ref first: the server fails",
        "# closed at startup if a level above READ_ONLY is reachable without an audit",
        "# signing key.",
        "#",
        "# Each profile below is UNVERIFIED until you export its",
        "# ORACLE_<NAME>_PASSWORD and run `oraclemcp doctor --online`.",
    ];
    lines.join("\n")
}

/// Render a discovery [`DiscoverySynthesis`] into the annotated `profiles.toml`.
///
/// The output parses through [`crate::OracleMcpConfig::from_toml_str`] and
/// satisfies `deny_unknown_fields`.
///
/// This bead (`.7`) renders the top-level bootable keys, the read-only-safety
/// comment block, and each profile's bootable minimum (with `max_level` /
/// `default_level` SET to `READ_ONLY`). The annotated writer bead (`.8`) extends
/// it with `monitor_profile`, the `[http]`/`[audit]` pointers, and the full
/// commented optional-field menu.
#[must_use]
pub fn render_annotated_config(synth: &DiscoverySynthesis) -> String {
    let mut out = String::new();

    out.push_str(
        "# oraclemcp profiles.toml — generated by `oraclemcp setup --discover`.\n\
         # Governed, least-privilege connection profiles (read-only by default).\n\
         # Self-documenting: required keys are set; every optional key is present\n\
         # but commented with a one-line help string using its exact name, so\n\
         # uncommenting yields a valid key. See oraclemcp.example.toml for the full\n\
         # worked reference and docs/configuration.md for the field reference.\n",
    );
    out.push('\n');

    // ── Top-level ──────────────────────────────────────────────────────────
    out.push_str("schema_version = 2\n");
    if let Some(default_profile) = &synth.default_profile {
        out.push_str(&format!(
            "default_profile = {}\n",
            toml_basic_string(default_profile)
        ));
    }
    out.push('\n');

    out.push_str(&read_only_safety_comment());
    out.push('\n');

    for synth_profile in &synth.profiles {
        out.push('\n');
        out.push_str(&render_profile_block(synth_profile));
    }

    out
}

/// Render one `[[profiles]]` block.
///
/// Bead `.7` renders the bootable minimum plus the needs-verification marker.
/// Bead `.8` extends this with the full commented optional-field menu.
fn render_profile_block(synth_profile: &SynthesizedProfile) -> String {
    let profile = &synth_profile.profile;
    let plan = &synth_profile.plan;
    let mut out = String::new();

    out.push_str("[[profiles]]\n");
    out.push_str(&format!(
        "# Unverified until you export {} and run `oraclemcp doctor --online`.\n",
        plan.password_env_var
    ));

    // name / description / connect_string / credential_ref (bootable minimum).
    out.push_str(&format!("name = {}\n", toml_basic_string(&profile.name)));
    if let Some(description) = &profile.description {
        out.push_str(&format!(
            "description = {}\n",
            toml_basic_string(description)
        ));
    }
    if let Some(connect_string) = &profile.connect_string {
        out.push_str(&format!(
            "connect_string = {}\n",
            toml_basic_string(connect_string)
        ));
    }
    // username is left commented — discovery never guesses a real account.
    out.push_str(
        "# username = \"APP_READONLY\"   # Oracle username; set only when a \
         least-privilege convention is known, else leave commented.\n",
    );
    if let Some(credential_ref) = &profile.credential_ref {
        out.push_str(&format!(
            "credential_ref = {}\n",
            toml_basic_string(credential_ref)
        ));
    }

    // The READ_ONLY safety ceiling, SET explicitly on both levels (bead `.7`).
    if let Some(max_level) = profile.max_level {
        out.push_str(&format!("max_level = \"{}\"\n", max_level.as_str()));
    }
    if let Some(default_level) = profile.default_level {
        out.push_str(&format!("default_level = \"{}\"\n", default_level.as_str()));
    }

    out
}

/// Quote and escape a string as a TOML basic string (`"…"`). Escapes `\`, `"`,
/// and the control characters that would otherwise be illegal in a basic
/// string, so an alias with an unusual character can never break the file.
fn toml_basic_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::OperatingLevel;
    use crate::OracleMcpConfig;
    use crate::discovery::synth::{DiscoveredNetService, SynthOptions, synthesize_profiles};

    fn synth(aliases: &[&str]) -> DiscoverySynthesis {
        let services: Vec<DiscoveredNetService> = aliases
            .iter()
            .map(|a| DiscoveredNetService::new(*a))
            .collect();
        synthesize_profiles(&services, &SynthOptions::default())
    }

    #[test]
    fn render_parses_through_strict_loader() {
        let rendered = render_annotated_config(&synth(&["SALES_RO", "HR_RO"]));
        let cfg = OracleMcpConfig::from_toml_str(&rendered)
            .expect("rendered config parses + validates through the strict loader");
        assert_eq!(cfg.profiles.len(), 2);
    }

    #[test]
    fn levels_are_set_read_only_in_rendered_toml() {
        let rendered = render_annotated_config(&synth(&["SALES_RO"]));
        assert!(
            rendered.contains("max_level = \"READ_ONLY\""),
            "max_level is SET to READ_ONLY in the rendered file (not defaulted)"
        );
        assert!(
            rendered.contains("default_level = \"READ_ONLY\""),
            "default_level is SET to READ_ONLY in the rendered file (not defaulted)"
        );
        // And it round-trips: the loaded profile really is READ_ONLY-capped.
        let cfg = OracleMcpConfig::from_toml_str(&rendered).expect("parses");
        assert_eq!(cfg.profiles[0].max_level, Some(OperatingLevel::ReadOnly));
        assert_eq!(
            cfg.profiles[0].default_level,
            Some(OperatingLevel::ReadOnly)
        );
    }

    #[test]
    fn least_privilege_and_audit_escalation_comments_present() {
        let rendered = render_annotated_config(&synth(&["SALES_RO"]));
        // Least-privilege account guidance.
        assert!(
            rendered.contains("CONNECT and SELECT"),
            "least-privilege account guidance is present"
        );
        assert!(
            rendered.contains("never an application-owner"),
            "guidance warns against an application-owner / SYSDBA account"
        );
        // Audit-before-escalation safety note.
        assert!(
            rendered.contains("[audit].key_ref"),
            "the audit-before-escalation note names [audit].key_ref"
        );
        assert!(
            rendered.contains("above READ_ONLY") && rendered.contains("fails"),
            "the note ties raising a level above READ_ONLY to failing closed"
        );
    }

    #[test]
    fn needs_verification_marker_is_rendered() {
        let rendered = render_annotated_config(&synth(&["SALES_RO"]));
        assert!(
            rendered.contains("Unverified until you export ORACLE_SALES_RO_PASSWORD"),
            "each profile carries a needs-verification marker naming its env var"
        );
    }

    #[test]
    fn honesty_no_over_claiming_framing() {
        // The writer's own rendered text must pass the honesty posture: no
        // "safe-by-default" / "read-only binary" / "fully audited" framing.
        let rendered = render_annotated_config(&synth(&["SALES_RO"])).to_ascii_lowercase();
        for forbidden in ["safe-by-default", "read-only binary", "fully audited"] {
            assert!(
                !rendered.contains(forbidden),
                "rendered output must not use the framing {forbidden:?}"
            );
        }
    }
}
