//! The annotated safe-config writer (TNS-onboarding beads `.7`, `.8`; design
//! spec §C, `docs/tns-discovery-onboarding.md`).
//!
//! Renders a discovery [`DiscoverySynthesis`] into a self-documenting
//! `profiles.toml`: a **bootable minimum** (the keys required for a valid,
//! governed, least-privilege profile — read-only by default) plus a
//! **self-documenting commented menu** (every remaining optional key present but
//! commented, each with a one-line help string using its exact serde name, so
//! uncommenting yields a valid key).
//!
//! The output round-trips through [`crate::OracleMcpConfig::from_toml_str`] —
//! both `OracleMcpConfig` and [`crate::ConnectionProfile`] are
//! `#[serde(deny_unknown_fields)]`, so every uncommented key MUST be a real
//! serde field and no unknown key may ever appear.
//!
//! # Read-only-safe posture (bead `.7`)
//!
//! Every synthesized profile is capped at `READ_ONLY` on both `max_level` and
//! `default_level`, and those levels are written **explicitly** (never left to a
//! struct default) so the safety ceiling is legible in the file. The writer also
//! emits, once near the top, a [`read_only_safety_comment`] block carrying the
//! least-privilege database-account guidance and the audit-before-escalation
//! safety note. Discovery never marks a profile `protected` or raises a level;
//! an unverified profile stays `READ_ONLY` and is flagged needs-verification.

use crate::discovery::contract::{
    CONNECTION_PROFILE_FIELD_DISPOSITIONS, Disposition, FieldDisposition,
    TOP_LEVEL_FIELD_DISPOSITIONS,
};
use crate::discovery::synth::{DiscoverySynthesis, SynthesizedProfile};

/// The commented, governed/least-privilege safety block the writer emits once
/// near the top of the file (bead `.7`). It states the read-only-by-default
/// posture, the least-privilege database-account guidance, and the
/// audit-before-escalation safety note.
///
/// Every line is already a `#` TOML comment, so the block can be embedded
/// verbatim and the file still parses.
#[must_use]
pub fn read_only_safety_comment() -> String {
    // Framing note: governed, least-privilege / read-only by default. Keep this
    // wording aligned with the honesty-grep gate (no over-claiming framing).
    let lines = [
        "# ── Governed, least-privilege posture (read-only by default) ──────────────",
        "# Discovery writes every profile capped at READ_ONLY on BOTH max_level and",
        "# default_level, set explicitly so the ceiling is legible here and never",
        "# relies on a default. A profile is not marked protected and no level is",
        "# raised on your behalf.",
        "#",
        "# Least-privilege account: point credential_ref at a DEDICATED Oracle",
        "# account granted only CONNECT and SELECT — never an application-owner or",
        "# SYSDBA/SYSTEM login. The password lives only in the environment variable",
        "# the discovery report names; it is never written to this file.",
        "#",
        "# Before you raise any profile's max_level above READ_ONLY, deliberately",
        "# edit that max_level AND configure [audit].key_ref first: the server fails",
        "# closed at startup if a level above READ_ONLY is reachable without an audit",
        "# signing key.",
        "#",
        "# Each profile below is UNVERIFIED until you export its",
        "# ORACLE_<NAME>_PASSWORD and run `oraclemcp doctor --online`.",
    ];
    lines.join("\n")
}

/// Render a discovery [`DiscoverySynthesis`] into the annotated `profiles.toml`
/// (design spec §C).
///
/// A **bootable minimum** (the SET keys of a valid, governed, least-privilege
/// profile) plus a **self-documenting commented menu**: every remaining serde
/// field of [`crate::OracleMcpConfig`] and [`crate::ConnectionProfile`] is
/// present but commented, each with a one-line help string using its exact serde
/// name. Both structs are `#[serde(deny_unknown_fields)]`, so every uncommented
/// key is a real field and no unknown key appears; the output round-trips
/// through [`crate::OracleMcpConfig::from_toml_str`].
///
/// The render is driven by the disposition tables
/// ([`TOP_LEVEL_FIELD_DISPOSITIONS`] / [`CONNECTION_PROFILE_FIELD_DISPOSITIONS`])
/// so a new serde field cannot be added without surfacing here — the parity /
/// anti-rot test (bead `.9`) fails until the writer renders it.
#[must_use]
pub fn render_annotated_config(synth: &DiscoverySynthesis) -> String {
    let mut out = String::new();

    out.push_str(
        "# oraclemcp profiles.toml — generated by `oraclemcp setup --discover`.\n\
         # Governed, least-privilege connection profiles (read-only by default).\n\
         # Self-documenting: required keys are set; every optional key is present\n\
         # but commented with a one-line help string using its exact name, so\n\
         # uncommenting yields a valid key. See oraclemcp.example.toml for the full\n\
         # worked reference and docs/configuration.md for the field reference.\n",
    );
    out.push('\n');

    render_top_level(&mut out, synth);

    out.push('\n');
    out.push_str(&read_only_safety_comment());
    out.push('\n');

    for synth_profile in &synth.profiles {
        out.push('\n');
        out.push_str(&render_profile_block(synth_profile));
    }

    out
}

/// Render the six top-level [`crate::OracleMcpConfig`] fields, driven by
/// [`TOP_LEVEL_FIELD_DISPOSITIONS`] so all six are surfaced (bead `.8`/`.9`).
fn render_top_level(out: &mut String, synth: &DiscoverySynthesis) {
    for fd in TOP_LEVEL_FIELD_DISPOSITIONS {
        match fd.field {
            "schema_version" => out.push_str("schema_version = 2\n"),
            "default_profile" => match &synth.default_profile {
                Some(default_profile) => out.push_str(&format!(
                    "default_profile = {}\n",
                    toml_basic_string(default_profile)
                )),
                // Ambiguous (many profiles): leave it commented — the loader
                // rejects a default_profile naming no profile.
                None => {
                    push_help(out, fd.help);
                    out.push_str("# default_profile = \"pick_one\"\n");
                }
            },
            "monitor_profile" => {
                push_help(out, fd.help);
                out.push_str("# monitor_profile = \"monitor_ro\"\n");
            }
            // http / audit are POINTERs: a short commented pointer to
            // oraclemcp.example.toml, never a reproduction of the surface.
            "http" | "audit" => {
                out.push('\n');
                push_help(out, fd.help);
            }
            // The [[profiles]] array is structural — rendered as blocks below.
            "profiles" => {}
            _ => {}
        }
    }
}

/// Render one `[[profiles]]` block: the bootable minimum plus the full commented
/// optional-field menu, driven by [`CONNECTION_PROFILE_FIELD_DISPOSITIONS`].
///
/// All scalar keys (SET and commented) are emitted before any `[profiles.*]`
/// sub-table header, so that uncommenting a commented scalar never lands it
/// inside the wrong sub-table.
fn render_profile_block(synth_profile: &SynthesizedProfile) -> String {
    let profile = &synth_profile.profile;
    let plan = &synth_profile.plan;

    let mut scalars = String::new();
    let mut sections = String::new();

    for fd in CONNECTION_PROFILE_FIELD_DISPOSITIONS {
        match fd.field {
            // ── SET (bootable minimum) ──────────────────────────────────────
            "name" => scalars.push_str(&format!("name = {}\n", toml_basic_string(&profile.name))),
            "description" => {
                if let Some(description) = &profile.description {
                    scalars.push_str(&format!(
                        "description = {}\n",
                        toml_basic_string(description)
                    ));
                }
            }
            "connect_string" => {
                if let Some(connect_string) = &profile.connect_string {
                    scalars.push_str(&format!(
                        "connect_string = {}\n",
                        toml_basic_string(connect_string)
                    ));
                }
            }
            "credential_ref" => {
                if let Some(credential_ref) = &profile.credential_ref {
                    scalars.push_str(&format!(
                        "credential_ref = {}\n",
                        toml_basic_string(credential_ref)
                    ));
                }
            }
            "max_level" => {
                if let Some(max_level) = profile.max_level {
                    scalars.push_str(&format!("max_level = \"{}\"\n", max_level.as_str()));
                }
            }
            "default_level" => {
                if let Some(default_level) = profile.default_level {
                    scalars.push_str(&format!("default_level = \"{}\"\n", default_level.as_str()));
                }
            }
            // ── SET-WHEN-KNOWN: username, not known here → commented ─────────
            "username" => push_commented_scalar(&mut scalars, fd, "\"APP_READONLY\""),
            // ── COMMENTED scalars ───────────────────────────────────────────
            "login_script" => {
                push_commented_scalar(&mut scalars, fd, "\"/home/operator/login.sql\"");
            }
            "login_statements" => push_commented_scalar(
                &mut scalars,
                fd,
                "[\"ALTER SESSION SET NLS_LANGUAGE = english\"]",
            ),
            "trusted_session_statements" => push_commented_scalar(
                &mut scalars,
                fd,
                "[\"BEGIN DBMS_OUTPUT.ENABLE(500000); END;\"]",
            ),
            "session_release_statements" => {
                push_commented_scalar(&mut scalars, fd, "[\"BEGIN NULL; END;\"]");
            }
            "logoff_statements" => {
                push_commented_scalar(&mut scalars, fd, "[\"BEGIN NULL; END;\"]");
            }
            "call_timeout_seconds" => push_commented_scalar(&mut scalars, fd, "30"),
            "max_query_cost" => push_commented_scalar(&mut scalars, fd, "100000"),
            "connect_timeout_seconds" => push_commented_scalar(&mut scalars, fd, "20"),
            "inactivity_timeout_seconds" => push_commented_scalar(&mut scalars, fd, "300"),
            "keepalive_minutes" => push_commented_scalar(&mut scalars, fd, "10"),
            "sdu" => push_commented_scalar(&mut scalars, fd, "32768"),
            // protected = true is the safe, instructive value: it pins the
            // ceiling immutable and requires max_level = READ_ONLY (which we set).
            "protected" => push_commented_scalar(&mut scalars, fd, "true"),
            "require_signed_tools" => push_commented_scalar(&mut scalars, fd, "true"),
            "read_only_standby" => push_commented_scalar(&mut scalars, fd, "false"),
            // CQN registration is a separate privileged operation and stays
            // disabled until an operator explicitly opts this profile in.
            "allow_change_notification" => push_commented_scalar(&mut scalars, fd, "false"),
            "max_subscriptions" => push_commented_scalar(&mut scalars, fd, "4"),
            // mcp_exposed = false is the instructive opt-out value.
            "mcp_exposed" => push_commented_scalar(&mut scalars, fd, "false"),
            "dashboard_ddl_workbench" => push_commented_scalar(&mut scalars, fd, "false"),
            // base is a scalar — must precede any sub-table header, so it lives
            // with the scalars even though it is last in the disposition table.
            "base" => push_commented_scalar(&mut scalars, fd, "\"another_profile\""),
            // ── COMMENTED sections ──────────────────────────────────────────
            "cumulative_query_cost_budget" => {
                push_help(&mut sections, fd.help);
                sections.push_str("# [profiles.cumulative_query_cost_budget]\n");
                sections.push_str("# max_cost = 500000\n");
                sections.push_str("# window_seconds = 3600\n");
            }
            "session_identity" => {
                push_help(&mut sections, fd.help);
                sections.push_str("# [profiles.session_identity]\n");
                sections.push_str("# program = \"oraclemcp\"\n");
                sections.push_str("# module = \"oraclemcp\"\n");
                sections.push_str("# action = \"inspect\"\n");
                sections.push_str("# client_identifier = \"agent\"\n");
            }
            "pool" => {
                push_help(&mut sections, fd.help);
                sections.push_str("# [profiles.pool]\n");
                sections.push_str("# max_size = 4\n");
                sections.push_str("# min_idle = 1\n");
                sections.push_str("# acquire_timeout_secs = 5\n");
                sections.push_str("# statement_cache_size = 50\n");
            }
            "oci" => {
                push_help(&mut sections, fd.help);
                sections.push_str("# [profiles.oci]\n");
                sections.push_str("# wallet_location = \"/etc/oracle/wallet\"\n");
                // A TCPS / wallet target additionally surfaces the wallet-password
                // secret-ref placeholder (bead `.6`) — never a literal.
                if let Some(wallet_env) = &plan.wallet_password_env_var {
                    sections.push_str(&format!("# wallet_password_ref = \"env:{wallet_env}\"\n"));
                }
            }
            "drcp" => {
                push_help(&mut sections, fd.help);
                sections.push_str("# [profiles.drcp]\n");
                sections.push_str("# pooled = true\n");
                sections.push_str("# connection_class = \"ORACLE_MCP_AGENTS\"\n");
                sections.push_str("# purity = \"reuse\"\n");
            }
            "proxy_auth" => {
                push_help(&mut sections, fd.help);
                sections.push_str("# [profiles.proxy_auth]\n");
                sections.push_str("# proxy_user = \"MCP_PROXY\"\n");
                sections.push_str("# target_schema = \"APP_OWNER\"\n");
            }
            "app_context" => {
                push_help(&mut sections, fd.help);
                sections.push_str("# [[profiles.app_context]]\n");
                sections.push_str("# namespace = \"ORACLEMCP_CTX\"\n");
                sections.push_str("# key = \"tenant_id\"\n");
                sections.push_str("# value = \"tenant-123\"\n");
            }
            "masking" => {
                push_help(&mut sections, fd.help);
                sections.push_str("# [profiles.masking]\n");
                sections.push_str("# mask_unknown_default = true\n");
                sections.push_str("# salt_ref = \"profile:sample:masking:v1\"\n");
                sections.push_str("# [[profiles.masking.rules]]\n");
                sections.push_str("# column_match = { column = \"EMAIL\" }\n");
                sections.push_str("# action = \"mask\"\n");
                sections.push_str("# tag = \"pii.email\"\n");
            }
            "sql_policy" => {
                push_help(&mut sections, fd.help);
                sections.push_str("# [profiles.sql_policy]\n");
                sections.push_str("# version = 1\n");
                sections.push_str("# [[profiles.sql_policy.rules]]\n");
                sections.push_str("# id = \"deny-payroll-read\"\n");
                sections.push_str(
                    "# match = { schema = \"HR\", object = \"PAYROLL\", verb = \"select\" }\n",
                );
                sections.push_str("# effect = { kind = \"deny\" }\n");
            }
            _ => {}
        }
    }

    let mut out = String::new();
    out.push_str("[[profiles]]\n");
    out.push_str(&format!(
        "# Unverified until you export {} and run `oraclemcp doctor --online`.\n",
        plan.password_env_var
    ));
    out.push_str(&scalars);
    if !sections.is_empty() {
        out.push_str(&sections);
    }
    out
}

/// Append a `# <help>` comment line.
fn push_help(out: &mut String, help: &str) {
    out.push_str(&format!("# {help}\n"));
}

/// Append a commented scalar menu entry: a `# <help>` help line followed by a
/// `# <field> = <example>` line whose key, when uncommented, is a valid serde
/// field (design spec §C — exact serde name).
fn push_commented_scalar(out: &mut String, fd: &FieldDisposition, example: &str) {
    debug_assert!(
        matches!(
            fd.disposition,
            Disposition::Commented | Disposition::SetWhenKnown
        ),
        "only commented / set-when-known fields render as a commented scalar",
    );
    push_help(out, fd.help);
    out.push_str(&format!("# {} = {example}\n", fd.field));
}

/// Quote and escape a string as a TOML basic string (`"…"`). Escapes `\`, `"`,
/// and the control characters that would otherwise be illegal in a basic
/// string, so an alias with an unusual character can never break the file.
fn toml_basic_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::OperatingLevel;
    use crate::OracleMcpConfig;
    use crate::discovery::synth::{DiscoveredNetService, SynthOptions, synthesize_profiles};

    fn synth(aliases: &[&str]) -> DiscoverySynthesis {
        let services: Vec<DiscoveredNetService> = aliases
            .iter()
            .map(|a| DiscoveredNetService::new(*a))
            .collect();
        synthesize_profiles(&services, &SynthOptions::default())
    }

    /// The canonical two-net-service golden input: one plain alias and one
    /// TCPS + wallet target (so the `[profiles.oci] wallet_password_ref`
    /// placeholder path is exercised).
    fn golden_synth() -> DiscoverySynthesis {
        let mut tcps = DiscoveredNetService::new("PRIMARY_TCPS");
        tcps.protocol = Some("TCPS".to_owned());
        tcps.host = Some("tcps.example.com".to_owned());
        tcps.port = Some(2484);
        tcps.service_name = Some("PRIMARY.example.com".to_owned());
        tcps.wallet_location = Some("/etc/oracle/wallet/primary".to_owned());
        let services = vec![DiscoveredNetService::new("SALES_RO"), tcps];
        synthesize_profiles(&services, &SynthOptions::default())
    }

    #[test]
    fn golden_snapshot_matches() {
        let rendered = render_annotated_config(&golden_synth());
        let golden = include_str!("../../tests/golden/discovery_annotated.toml");
        if std::env::var_os("OMCP_UPDATE_GOLDEN").is_some() {
            std::fs::write(
                concat!(
                    env!("CARGO_MANIFEST_DIR"),
                    "/tests/golden/discovery_annotated.toml"
                ),
                &rendered,
            )
            .expect("write golden");
        }
        assert_eq!(
            rendered, golden,
            "annotated writer output drifted from the golden snapshot — review the \
             change, then re-run with OMCP_UPDATE_GOLDEN=1 to regenerate"
        );
        // The golden is not just text: it must parse through the strict loader.
        OracleMcpConfig::from_toml_str(golden).expect("golden parses + validates");
    }

    #[test]
    fn render_parses_through_strict_loader() {
        let rendered = render_annotated_config(&synth(&["SALES_RO", "HR_RO"]));
        let cfg = OracleMcpConfig::from_toml_str(&rendered)
            .expect("rendered config parses + validates through the strict loader");
        assert_eq!(cfg.profiles.len(), 2);
    }

    #[test]
    fn levels_are_set_read_only_in_rendered_toml() {
        let rendered = render_annotated_config(&synth(&["SALES_RO"]));
        assert!(
            rendered.contains("max_level = \"READ_ONLY\""),
            "max_level is SET to READ_ONLY in the rendered file (not defaulted)"
        );
        assert!(
            rendered.contains("default_level = \"READ_ONLY\""),
            "default_level is SET to READ_ONLY in the rendered file (not defaulted)"
        );
        // And it round-trips: the loaded profile really is READ_ONLY-capped.
        let cfg = OracleMcpConfig::from_toml_str(&rendered).expect("parses");
        assert_eq!(cfg.profiles[0].max_level, Some(OperatingLevel::ReadOnly));
        assert_eq!(
            cfg.profiles[0].default_level,
            Some(OperatingLevel::ReadOnly)
        );
    }

    #[test]
    fn least_privilege_and_audit_escalation_comments_present() {
        let rendered = render_annotated_config(&synth(&["SALES_RO"]));
        // Least-privilege account guidance.
        assert!(
            rendered.contains("CONNECT and SELECT"),
            "least-privilege account guidance is present"
        );
        assert!(
            rendered.contains("never an application-owner"),
            "guidance warns against an application-owner / SYSDBA account"
        );
        // Audit-before-escalation safety note.
        assert!(
            rendered.contains("[audit].key_ref"),
            "the audit-before-escalation note names [audit].key_ref"
        );
        assert!(
            rendered.contains("above READ_ONLY") && rendered.contains("fails"),
            "the note ties raising a level above READ_ONLY to failing closed"
        );
    }

    #[test]
    fn needs_verification_marker_is_rendered() {
        let rendered = render_annotated_config(&synth(&["SALES_RO"]));
        assert!(
            rendered.contains("Unverified until you export ORACLE_SALES_RO_PASSWORD"),
            "each profile carries a needs-verification marker naming its env var"
        );
    }

    #[test]
    fn honesty_no_over_claiming_framing() {
        // The writer's own rendered text must pass the honesty posture; the
        // forbidden phrases below are negative examples asserted ABSENT.
        let rendered = render_annotated_config(&synth(&["SALES_RO"])).to_ascii_lowercase();
        let forbidden_framings = ["safe-by-default", "read-only binary", "fully audited"]; // honesty-allow: negative examples asserted absent
        for forbidden in forbidden_framings {
            assert!(
                !rendered.contains(forbidden),
                "rendered output must not use the forbidden framing {forbidden:?}"
            );
        }
    }

    // ---- bead .8: full annotated menu (all fields, optional commented) ----

    /// Extract the set of config keys the rendered output touches — each serde
    /// field name that appears either SET (`key =`) or commented
    /// (`# key =`, `# [profiles.key]`, `# [[profiles.key]]`).
    fn rendered_profile_keys(rendered: &str) -> std::collections::BTreeSet<String> {
        use crate::discovery::contract::CONNECTION_PROFILE_FIELD_DISPOSITIONS;
        let mut present = std::collections::BTreeSet::new();
        for fd in CONNECTION_PROFILE_FIELD_DISPOSITIONS {
            let field = fd.field;
            let set_line = format!("\n{field} = ");
            let commented_scalar = format!("# {field} = ");
            let sub_table = format!("[profiles.{field}]");
            let sub_array = format!("[[profiles.{field}]]");
            if rendered.contains(&set_line)
                || rendered.contains(&commented_scalar)
                || rendered.contains(&sub_table)
                || rendered.contains(&sub_array)
            {
                present.insert(field.to_owned());
            }
        }
        present
    }

    #[test]
    fn every_connection_profile_serde_field_appears_set_or_commented() {
        use crate::discovery::contract::connection_profile_field_names;
        let rendered = render_annotated_config(&golden_synth());
        let present = rendered_profile_keys(&rendered);
        let expected: std::collections::BTreeSet<String> = connection_profile_field_names()
            .into_iter()
            .map(str::to_owned)
            .collect();
        assert_eq!(
            present,
            expected,
            "every ConnectionProfile serde field must appear SET or commented; \
             missing: {:?}",
            expected.difference(&present).collect::<Vec<_>>()
        );
    }

    #[test]
    fn every_top_level_field_is_represented() {
        let rendered = render_annotated_config(&synth(&["SALES_RO", "HR_RO"]));
        // schema_version SET; default_profile commented (ambiguous, 2 profiles);
        // monitor_profile commented; http/audit via the example.toml pointers;
        // profiles as [[profiles]] blocks.
        assert!(rendered.contains("\nschema_version = 2\n"));
        assert!(rendered.contains("# default_profile = "));
        assert!(rendered.contains("# monitor_profile = "));
        assert!(rendered.contains("oraclemcp.example.toml [http]"));
        assert!(rendered.contains("oraclemcp.example.toml [audit]"));
        assert!(rendered.contains("[[profiles]]"));
    }

    #[test]
    fn single_service_sets_default_profile_uncommented() {
        let rendered = render_annotated_config(&synth(&["SALES_RO"]));
        assert!(
            rendered.contains("\ndefault_profile = \"sales_ro\"\n"),
            "an unambiguous single service sets default_profile"
        );
    }

    #[test]
    fn oci_wallet_password_ref_only_for_tcps_or_wallet() {
        // Plain alias: no wallet_password_ref KEY line (the oci help string does
        // mention the field name in prose, so match the `key = ` form instead).
        let plain = render_annotated_config(&synth(&["SALES_RO"]));
        assert!(!plain.contains("wallet_password_ref = "));
        // TCPS/wallet target: the commented placeholder appears under oci.
        let golden = render_annotated_config(&golden_synth());
        assert!(
            golden.contains("# wallet_password_ref = \"env:ORACLE_PRIMARY_TCPS_WALLET_PASSWORD\"")
        );
    }

    #[test]
    fn no_literal_secret_value_is_emitted() {
        // The word "literal:" may appear in the `protected` help (it warns that
        // protected rejects literal: refs), but no credential/wallet/key line may
        // carry a literal: VALUE.
        let rendered = render_annotated_config(&golden_synth());
        for line in rendered.lines() {
            let trimmed = line.trim_start_matches("# ").trim();
            if trimmed.starts_with("credential_ref")
                || trimmed.starts_with("wallet_password_ref")
                || trimmed.starts_with("key_ref")
            {
                assert!(
                    !trimmed.contains("\"literal:"),
                    "no secret line may carry a literal: value: {line}"
                );
            }
        }
    }

    #[test]
    fn uncommenting_a_sampled_scalar_and_section_still_parses() {
        let rendered = render_annotated_config(&golden_synth());
        // Uncomment call_timeout_seconds (a scalar; valid under each profile) and
        // the FIRST [profiles.oci] section together with its wallet_location key,
        // leaving every other commented line untouched. Uncommenting a section
        // key without its header would land it in the wrong table, so the header
        // and its one key must be uncommented as a unit.
        let mut oci_header_done = false;
        let mut in_first_oci = false;
        let mut wallet_done = false;
        let mut uncommented = String::new();
        for line in rendered.lines() {
            let mut emit = line.to_owned();
            if line == "# call_timeout_seconds = 30" {
                emit = "call_timeout_seconds = 30".to_owned();
            } else if !oci_header_done && line == "# [profiles.oci]" {
                oci_header_done = true;
                in_first_oci = true;
                emit = "[profiles.oci]".to_owned();
            } else if in_first_oci
                && !wallet_done
                && line == "# wallet_location = \"/etc/oracle/wallet\""
            {
                wallet_done = true;
                in_first_oci = false;
                emit = "wallet_location = \"/etc/oracle/wallet\"".to_owned();
            }
            uncommented.push_str(&emit);
            uncommented.push('\n');
        }
        let cfg = OracleMcpConfig::from_toml_str(&uncommented)
            .expect("uncommenting a sampled scalar + section still parses");
        let first = &cfg.profiles[0];
        assert_eq!(first.call_timeout_seconds, Some(30));
        assert!(first.oci.is_some(), "the uncommented [profiles.oci] loaded");
    }
}
