#!/usr/bin/env bash
# no-self-fulfilling-fixture lint (H7 / plan §30.5, §30.6).
#
# The recurring trap this lint targets (surfaced by driver bead DC1 and
# generalized in PLAN_ENGINEERING_PROGRAM.md §30.5): a conformance/golden test
# whose "expected" value is produced by invoking the exact same code path as
# the "actual" value under test. Such an assertion can never fail regardless
# of whether the code under test is correct — it is self-fulfilling by
# construction.
#
# Heuristic (deliberately narrow, to keep false positives at zero on a clean
# tree): for every `assert_eq!(A, B, ...)` in test code, compare A and B as
# literally written (normalized whitespace only — no variable-binding
# resolution). If A and B are textually identical AND the expression invokes a
# function/macro (contains a call), the assertion can never distinguish
# correct from broken code — flag it.
#
# Deliberately NOT attempted: resolving A/B through earlier `let` bindings
# (e.g. `let before = f(x); ...; assert_eq!(f(x), before)`). This codebase's
# dominant pattern is the OPPOSITE of self-fulfilling — a snapshot taken
# before a state-changing action, re-read after, asserted unchanged (or
# advanced) as a genuine regression check (`before_list`/`baseline`/
# `gen_at_mint`-style names throughout dispatch/tests.rs, client_credentials.rs,
# sink.rs, …). A naive same-function-scope let-resolution pass was tried during
# this lint's development and flagged ~20 of exactly those legitimate
# invariant checks with zero true positives — a class of false positive, not a
# tightened true positive, so it was dropped in favor of syntactic-only
# comparison, which alone already catches the DC1 shape (see the self-test).
#
# Scope: files under a `tests/` directory (`*.rs`) and files named `tests.rs`
# / `*_tests.rs` are scanned whole; other `src/*.rs` files are scanned only
# from their first `#[cfg(test)]` marker onward, so production code is never
# in scope.
#
# What this lint deliberately does NOT do: verify golden/snapshot (.json/.snap)
# fixture *provenance* end-to-end (was the file ever independently reviewed,
# not just regenerated by the code it pins). Inline self-comparison is a
# static property this script can prove; "was a human eyes-on the diff" is a
# process control — see tests/golden/PROVENANCE.md's review rule and
# docs/test-tiers.md, not this script.
#
# Escape hatch: a `fixture-lint:allow: <reason>` marker inside the
# `assert_eq!(...)` call (e.g. its message argument) or anywhere in the
# unbroken `//` comment block directly above it suppresses that one finding.
# Reserved for the rare case where comparing a call to
# itself is the deliberate point of the test — e.g. proving a `PartialEq`
# impl is not vacuously false (reflexivity), which matters right next to
# `assert_ne!` checks that would otherwise pass for free if equality were
# broken. `crates/oraclemcp-guard/tests/classifier_metamorphic.rs`'s
# "classification is deterministic" check is the one instance today; every use
# must justify itself the same way, not just cite this comment.
#
# Usage:
#   bash scripts/oraclemcp_fixture_lint.sh             # scan the tracked tree
#   bash scripts/oraclemcp_fixture_lint.sh --self-test  # prove the lint trips
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SELFTEST=false
if [[ "${1:-}" == --self-test ]]; then
  SELFTEST=true
fi

run_selftest() {
  local scratch_dir scratch_file
  scratch_dir="$(mktemp -d)"
  trap 'rm -rf "$scratch_dir"' RETURN
  scratch_file="$scratch_dir/injected_self_fulfilling_tests.rs"

  # A planted fixture whose "expected" value is produced by invoking the exact
  # same code path as the "actual" value — the DC1 shape. This must never pass
  # the lint; it always compares serialize_cell's own output to itself.
  cat >"$scratch_file" <<'RS'
use oraclemcp_db::{OracleCell, SerializeOptions, serialize_cell};

#[test]
fn self_fulfilling_injected_by_fixture_lint_selftest() {
    let cell = OracleCell::new("NUMBER", Some("42".to_owned()));
    assert_eq!(
        serialize_cell(&cell, &SerializeOptions::default()),
        serialize_cell(&cell, &SerializeOptions::default())
    );
}
RS

  echo "oraclemcp-fixture-lint: self-test - planted fixture at $scratch_file" >&2
  if ORACLEMCP_FIXTURE_LINT_SELFTEST_PATH="$scratch_file" bash "${BASH_SOURCE[0]}"; then
    echo "oraclemcp-fixture-lint: self-test FAILED (lint did not trip on a planted self-fulfilling fixture)" >&2
    return 1
  fi
  echo "oraclemcp-fixture-lint: self-test OK (lint correctly rejects the planted fixture)" >&2
  return 0
}

if $SELFTEST; then
  run_selftest
  exit $?
fi

export ORACLEMCP_FIXTURE_LINT_ROOT="$ROOT"
export ORACLEMCP_FIXTURE_LINT_SELFTEST_PATH="${ORACLEMCP_FIXTURE_LINT_SELFTEST_PATH:-}"

python3 - <<'PY'
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(os.environ["ORACLEMCP_FIXTURE_LINT_ROOT"])
SELFTEST_PATH = os.environ.get("ORACLEMCP_FIXTURE_LINT_SELFTEST_PATH", "")
ALLOW_MARKER = "fixture-lint:allow"


def candidate_files() -> list[Path]:
    if SELFTEST_PATH:
        return [Path(SELFTEST_PATH)]
    output = subprocess.check_output(["git", "ls-files", "*.rs"], cwd=ROOT, text=True)
    return [ROOT / line for line in output.splitlines()]


def in_scope_text(path: Path, text: str) -> tuple[str, int] | None:
    """Return (scanned_text, line_offset) or None if the file is out of scope.

    Whole-file scope for anything under a `tests/` directory or named
    `tests.rs` / `*_tests.rs`; `#[cfg(test)]`-onward scope for other `src/`
    files; everything else (build scripts, non-test src) is out of scope so
    production code is never scanned.
    """
    rel = path.as_posix()
    is_test_path = (
        "/tests/" in f"/{rel}"
        or rel.endswith("/tests.rs")
        or rel == "tests.rs"
        or rel.endswith("_tests.rs")
    )
    if is_test_path:
        return text, 0
    marker = "#[cfg(test)]"
    idx = text.find(marker)
    if idx == -1:
        return None
    line_offset = text.count("\n", 0, idx)
    return text[idx:], line_offset


CALL_NAMES = ("assert_eq!",)


def find_calls(text: str) -> list[tuple[int, str]]:
    """Return (start_offset, inner_args_text) for each assert_eq!( ... ) call,
    with the inner text spanning balanced parens (string-literal aware)."""
    calls: list[tuple[int, str]] = []
    for name in CALL_NAMES:
        for m in re.finditer(re.escape(name) + r"\s*\(", text):
            open_idx = m.end() - 1
            end = _match_paren(text, open_idx)
            if end == -1:
                continue
            calls.append((m.start(), text[open_idx + 1 : end]))
    return calls


def _match_paren(text: str, open_idx: int) -> int:
    depth = 0
    in_str = False
    escaped = False
    i = open_idx
    while i < len(text):
        c = text[i]
        if in_str:
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == '"':
                in_str = False
        else:
            if c == '"':
                in_str = True
            elif c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    return i
        i += 1
    return -1


def split_top_level_args(s: str) -> list[str]:
    args: list[str] = []
    depth = 0
    cur: list[str] = []
    in_str = False
    escaped = False
    for c in s:
        if in_str:
            cur.append(c)
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == '"':
                in_str = False
            continue
        if c == '"':
            in_str = True
            cur.append(c)
        elif c in "([{":
            depth += 1
            cur.append(c)
        elif c in ")]}":
            depth -= 1
            cur.append(c)
        elif c == "," and depth == 0:
            args.append("".join(cur))
            cur = []
        else:
            cur.append(c)
    if cur:
        args.append("".join(cur))
    return [a.strip() for a in args]


def display_path(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def normalize(expr: str) -> str:
    return re.sub(r"\s+", " ", expr.strip())


def looks_like_call(expr: str) -> bool:
    return "(" in expr


def scan_file(path: Path) -> list[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return []
    scoped = in_scope_text(path, text)
    if scoped is None:
        return []
    scanned_text, line_offset = scoped

    line_starts = [0]
    for line in scanned_text.split("\n"):
        line_starts.append(line_starts[-1] + len(line) + 1)

    def line_of(offset: int) -> int:
        lo, hi = 0, len(line_starts) - 1
        while lo < hi:
            mid = (lo + hi + 1) // 2
            if line_starts[mid] <= offset:
                lo = mid
            else:
                hi = mid - 1
        return lo

    lines = scanned_text.split("\n")

    def leading_comment_block(line_idx: int) -> str:
        # Walk upward through the unbroken run of `//` comment lines directly
        # above `line_idx` (the marker's natural home), stopping at the first
        # non-comment line.
        j = line_idx - 1
        collected: list[str] = []
        while j >= 0 and lines[j].strip().startswith("//"):
            collected.append(lines[j])
            j -= 1
        return "\n".join(reversed(collected))

    findings: list[str] = []
    for start, inner in find_calls(scanned_text):
        # The marker may sit inside the call (e.g. its message argument) or in
        # the leading `//` comment block directly above it — check both, not
        # just the balanced-paren span.
        if ALLOW_MARKER in inner or ALLOW_MARKER in leading_comment_block(line_of(start)):
            continue
        args = split_top_level_args(inner)
        if len(args) < 2:
            continue
        a, b = normalize(args[0]), normalize(args[1])
        if a == b and looks_like_call(a):
            lineno = line_of(start) + 1 + line_offset
            findings.append(
                f"{display_path(path)}:{lineno}: "
                f"assert_eq!({args[0].strip()}, {args[1].strip()}) compares "
                f"the identical expression to itself — self-fulfilling (never "
                f"catches a wrong implementation): {a}"
            )
    return findings


def main() -> int:
    files = candidate_files()
    findings: list[str] = []
    scanned = 0
    for path in files:
        if not path.is_file():
            continue
        scanned += 1
        findings.extend(scan_file(path))

    if findings:
        print("oraclemcp-fixture-lint: FAIL", file=sys.stderr)
        for finding in findings:
            print(f"  SELF_FULFILLING: {finding}", file=sys.stderr)
        print(
            "oraclemcp-fixture-lint: an assertion whose two sides are the "
            "identical expression can never fail — it proves nothing about the "
            "code under test. Give the assertion an independently-derived "
            "expected value (a literal, a hand-computed value, or a different "
            "reference implementation), per plan §30.5.",
            file=sys.stderr,
        )
        return 1

    print(
        f"oraclemcp-fixture-lint: OK - no self-fulfilling fixtures found "
        f"({scanned} Rust file(s) scanned)."
    )
    return 0


sys.exit(main())
PY
