//! Read-only enforcement layers (plan §6.3) and the session-setting allowlist
//! (§6.5). Three complementary layers protect a read-only session, strongest
//! first:
//!
//! - **(A) DB-privilege ceiling** — a least-privilege Oracle user (operator's
//!   responsibility; see `docs/oraclemcp/least-privilege.md`). The only hard
//!   boundary.
//! - **(B) `SET TRANSACTION READ ONLY`** — issued whenever the session level is
//!   `READ_ONLY`, so a *misclassified* direct DML still raises `ORA-01456`.
//! - **(C) The fail-closed classifier** (P1-1) + the operating-level gate (P0-7).
//!
//! Caveat (carried everywhere): layer B does **not** stop
//! `PRAGMA AUTONOMOUS_TRANSACTION` side-effects fired by triggers/VPD functions
//! (they commit independently, no `ORA-01456`). The classifier's trigger/VPD
//! walk is the defense; on a `protected` profile, layer A is the real boundary.

use crate::levels::OperatingLevel;

/// The statement that makes the current transaction read-only at the engine.
pub const SET_TRANSACTION_READ_ONLY: &str = "SET TRANSACTION READ ONLY";

/// Session-setup statements to apply for a session at `level` on a profile
/// (`protected` = production). At `READ_ONLY` this issues
/// `SET TRANSACTION READ ONLY` (layer B).
///
/// Layering of `SET ROLE` / `ALTER SESSION` (the precise, code-true picture):
///
/// - **`SET ROLE`** is mapped by the classifier (layer C) to
///   `Destructive` / `OperatingLevel::Admin`, so the operating-level gate
///   ([`crate::levels::SessionLevelState::evaluate`]) never *Allows* it below
///   `ADMIN`: a `READ_ONLY` *or* `READ_WRITE` session is forced to step up to
///   `ADMIN` (and on a profile whose ceiling is below `ADMIN`, it is hard
///   `Blocked`). It is **not** classified `Forbidden`, so an operator who has
///   genuinely provisioned an `ADMIN` ceiling can still run it after step-up.
/// - **`ALTER SESSION SET <param>`** is tokenized by the shared policy below
///   before the classifier's operator allow-list. Strict, reviewed parameter
///   assignments are `Guarded` / `READ_WRITE` and marked non-transactional so
///   raw execution needs an exact-statement confirmation even with
///   `commit=false`. Every other `ALTER SESSION` form is `Forbidden` at every
///   operating level. The same policy is used by profile and dedicated-session
///   validation, so those paths cannot drift apart.
///
/// The hard guarantee that a session cannot enable a write-bearing role
/// post-connect rests on **layer A** (the least-privilege Oracle user, which has
/// no write-bearing role to enable); layers B and C are defense-in-depth that
/// refuse to silently *Allow* the attempt.
#[must_use]
pub fn read_only_setup_statements(level: OperatingLevel) -> Vec<&'static str> {
    if level == OperatingLevel::ReadOnly {
        vec![SET_TRANSACTION_READ_ONLY]
    } else {
        Vec::new()
    }
}

/// The allowlist of `ALTER SESSION SET <param>` parameters an agent may set at
/// `READ_ONLY` (§6.5): session-scoped, non-data-mutating, non-security.
const ALTER_SESSION_ALLOWLIST: &[&str] = &[
    "CURRENT_SCHEMA",
    "NLS_DATE_FORMAT",
    "NLS_TIMESTAMP_FORMAT",
    "NLS_TIMESTAMP_TZ_FORMAT",
    "NLS_NUMERIC_CHARACTERS",
    "NLS_LANGUAGE",
    "NLS_TERRITORY",
    "NLS_SORT",
    "NLS_COMP",
    "TIME_ZONE",
    "OPTIMIZER_MODE",
    "STATISTICS_LEVEL",
    "OPTIMIZER_DYNAMIC_SAMPLING",
    "PLSQL_WARNINGS",
    // Edition selection changes only the current session's edition view. Oracle
    // enforces the edition hierarchy itself; the server neither creates nor
    // models edition branches here.
    "EDITION",
    // Generated by `oracle_compile_object(plscope=true)`. This setting controls
    // compiler metadata collection for the current session; it does not change
    // the active container, privileges, auditing, tracing, or transaction mode.
    "PLSCOPE_SETTINGS",
];

/// The classifier-facing result of the shared `ALTER SESSION` policy.
///
/// `None` means the first executable tokens are not `ALTER SESSION`. `Some`
/// means they are, with the boolean recording whether the complete statement is
/// an allowlisted `ALTER SESSION SET` assignment.
pub(crate) fn alter_session_policy(stmt: &str) -> Option<bool> {
    if !starts_with_alter_session(stmt) {
        return None;
    }

    let allowed = normalize_significant_tokens(stmt).is_some_and(|normalized| {
        let upper = normalized.to_ascii_uppercase();
        let Some(rest) = upper.strip_prefix("ALTER SESSION SET ") else {
            return false;
        };
        let Some(params) = alter_session_params(rest) else {
            return false;
        };
        if params.is_empty() {
            return false;
        }
        params
            .iter()
            .all(|p| ALTER_SESSION_ALLOWLIST.contains(&p.as_str()))
    });

    Some(allowed)
}

/// Read the first two executable bare words while ignoring whitespace and SQL
/// comments. This deliberately stops after `ALTER SESSION`, so malformed text
/// later in the statement (for example an unterminated literal) is still
/// recognized as an ALTER SESSION attempt and therefore fails closed when the
/// full tokenizer rejects it.
fn starts_with_alter_session(stmt: &str) -> bool {
    let Some((first, rest)) = take_leading_word(stmt) else {
        return false;
    };
    if !first.eq_ignore_ascii_case("ALTER") {
        return false;
    }
    let Some((second, _)) = take_leading_word(rest) else {
        return false;
    };
    second.eq_ignore_ascii_case("SESSION")
}

fn take_leading_word(mut input: &str) -> Option<(&str, &str)> {
    loop {
        input = input.trim_start();
        if let Some(comment) = input.strip_prefix("--") {
            let line_end = comment.find(['\r', '\n'])?;
            input = &comment[line_end..];
            continue;
        }
        if let Some(comment) = input.strip_prefix("/*") {
            let end = comment.find("*/")?;
            input = &comment[end + 2..];
            continue;
        }
        break;
    }

    let end = input
        .char_indices()
        .take_while(|(_, ch)| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '$' | '#'))
        .map(|(offset, ch)| offset + ch.len_utf8())
        .last()?;
    Some((&input[..end], &input[end..]))
}

/// Canonicalize significant tokens while dropping comments and whitespace.
/// Separating every surviving token with one space makes comment wedges and
/// compact `name=value` spellings equivalent without ever interpreting text
/// inside a quoted literal as syntax.
fn normalize_significant_tokens(stmt: &str) -> Option<String> {
    use sqlparser::dialect::OracleDialect;
    use sqlparser::tokenizer::{Token, Tokenizer};

    let tokens = Tokenizer::new(&OracleDialect {}, stmt).tokenize().ok()?;
    let mut normalized = String::new();
    for token in tokens
        .iter()
        .filter(|token| !matches!(token, Token::Whitespace(_)))
    {
        if !normalized.is_empty() {
            normalized.push(' ');
        }
        normalized.push_str(&token.to_string());
    }
    Some(normalized)
}

/// Whether an `ALTER SESSION SET <param> = …` statement targets *only*
/// allowlisted, safe session parameters (§6.5). Oracle accepts multiple
/// space-separated `param = value` pairs in a single `ALTER SESSION SET`, so
/// **every** parameter assigned must be in the allowlist — a single allowlisted
/// prefix must NOT smuggle a trailing `SQL_TRACE = TRUE` / `EVENTS = '10046 …'`
/// past the gate (oracle-ajm2.4). Anything outside the allowlist (e.g. statements
/// that change security/audit/trace context) is rejected. Fail-closed: a
/// statement that cannot be cleanly parsed into known `param = value` pairs, or
/// that assigns zero parameters, is rejected. String-literal-aware so an `=` or
/// whitespace *inside* a quoted value is never mistaken for a parameter name.
/// Case-insensitive.
#[must_use]
pub fn is_allowed_alter_session(stmt: &str) -> bool {
    matches!(alter_session_policy(stmt), Some(true))
}

/// Parse the post-`ALTER SESSION SET ` remainder into the list of parameter
/// names being assigned. String-literal-aware: a single-quoted value is opaque,
/// so `=`/whitespace inside it never starts a new clause or parameter name.
///
/// The grammar accepted is a whitespace-separated sequence of `IDENT = VALUE`
/// clauses (Oracle's documented `param = value [param = value]...`). The
/// parameter name is the identifier token immediately preceding each top-level
/// `=`. Returns `None` (fail-closed) on anything that does not fit this shape:
/// an unterminated quote, a top-level `=` with no preceding identifier, or a
/// value clause that is not cleanly closed before the next parameter.
fn alter_session_params(rest: &str) -> Option<Vec<String>> {
    // Top-level tokenizer: words, the `=` sign, and opaque single-quoted strings.
    // Doubled `''` inside a literal is a quote escape, not a terminator.
    #[derive(PartialEq)]
    enum Tok {
        Word(String),
        Eq,
        Str,
    }
    let mut toks: Vec<Tok> = Vec::new();
    let mut chars = rest.chars().peekable();
    while let Some(&c) = chars.peek() {
        match c {
            c if c.is_whitespace() => {
                chars.next();
            }
            '=' => {
                chars.next();
                toks.push(Tok::Eq);
            }
            '\'' => {
                // Opaque string literal: consume until the closing quote,
                // honoring doubled-'' escapes. Unterminated → fail closed.
                chars.next();
                loop {
                    match chars.next() {
                        Some('\'') => {
                            if chars.peek() == Some(&'\'') {
                                chars.next(); // escaped quote, keep scanning
                            } else {
                                break;
                            }
                        }
                        Some(_) => {}
                        None => return None, // unterminated literal
                    }
                }
                toks.push(Tok::Str);
            }
            _ => {
                // A bare word: run of non-whitespace, non-`=`, non-quote chars.
                let mut word = String::new();
                while let Some(&w) = chars.peek() {
                    if w.is_whitespace() {
                        break;
                    }
                    if w == '=' {
                        break;
                    }
                    if w == '\'' {
                        break;
                    }
                    word.push(w);
                    chars.next();
                }
                if word.is_empty() {
                    return None;
                }
                toks.push(Tok::Word(word));
            }
        }
    }

    // Walk the token stream as repeated `WORD = (WORD|STR)` clauses; collect the
    // WORD before each `=` as a parameter name. Reject any other shape.
    // Fixed-size chunks make parser progress structural rather than dependent
    // on a mutable index. This keeps malformed input fail-closed and prevents
    // a corrupted/non-progressing index from repeatedly allocating forever.
    let mut clauses = toks.chunks_exact(3);
    if !clauses.remainder().is_empty() {
        return None;
    }
    let mut params: Vec<String> = Vec::with_capacity(clauses.len());
    for clause in &mut clauses {
        // param name
        let Tok::Word(name) = &clause[0] else {
            return None;
        };
        // `=`
        if clause[1] != Tok::Eq {
            return None;
        }
        // value: a word or a string literal
        match &clause[2] {
            Tok::Word(_) | Tok::Str => {}
            _ => return None,
        }
        params.push(name.trim().to_owned());
    }
    Some(params)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn read_only_level_sets_transaction_read_only() {
        assert_eq!(
            read_only_setup_statements(OperatingLevel::ReadOnly),
            vec![SET_TRANSACTION_READ_ONLY]
        );
        assert!(read_only_setup_statements(OperatingLevel::ReadWrite).is_empty());
        assert!(read_only_setup_statements(OperatingLevel::Ddl).is_empty());
    }

    #[test]
    fn alter_session_allowlist_permits_safe_params() {
        assert!(is_allowed_alter_session(
            "ALTER SESSION SET CURRENT_SCHEMA = HR"
        ));
        assert!(is_allowed_alter_session(
            "alter session set nls_date_format='YYYY'"
        ));
        assert!(is_allowed_alter_session(
            "ALTER SESSION SET OPTIMIZER_MODE = ALL_ROWS"
        ));
        assert!(is_allowed_alter_session(
            "ALTER SESSION SET PLSQL_WARNINGS = 'ENABLE:ALL'"
        ));
        assert!(is_allowed_alter_session(
            "ALTER SESSION SET EDITION = app_release_v2"
        ));
        assert!(is_allowed_alter_session(
            "ALTER SESSION SET PLSCOPE_SETTINGS = 'IDENTIFIERS:ALL, STATEMENTS:ALL'"
        ));
        assert!(is_allowed_alter_session(
            "/* oraclemcp profile=dev */ ALTER/**/SESSION SET CURRENT_SCHEMA/**/=/**/HR"
        ));
    }

    #[test]
    fn alter_session_allowlist_rejects_security_and_unknown() {
        // Security/audit context changes are rejected.
        assert!(!is_allowed_alter_session(
            "ALTER SESSION SET CONTAINER = CDB$ROOT"
        ));
        assert!(!is_allowed_alter_session(
            "ALTER SESSION SET SQL_TRACE = TRUE"
        ));
        assert!(!is_allowed_alter_session(
            "ALTER SESSION SET EDITIONING = TRUE"
        ));
        // SET ROLE is not an ALTER SESSION and is rejected here too.
        assert!(!is_allowed_alter_session("SET ROLE DBA"));
        assert!(!is_allowed_alter_session("DROP TABLE t"));
        assert!(!is_allowed_alter_session(
            "ALTER SESSION SET EVENTS '10046'"
        ));
    }

    #[test]
    fn alter_session_rejects_smuggled_trailing_param() {
        // oracle-ajm2.4: an allowlisted prefix must NOT smuggle a
        // non-allowlisted trailing parameter past the gate. Oracle accepts
        // multiple `param = value` pairs in one ALTER SESSION SET, so EVERY
        // assigned parameter must be allowlisted.
        assert!(
            !is_allowed_alter_session("ALTER SESSION SET CURRENT_SCHEMA=HR SQL_TRACE=TRUE"),
            "trailing SQL_TRACE must not be smuggled past an allowlisted prefix"
        );
        // ... including when the smuggled value is a quoted literal containing
        // spaces and `=` (EVENTS '10046 trace name context forever, level 12').
        assert!(
            !is_allowed_alter_session(
                "ALTER SESSION SET CURRENT_SCHEMA = HR EVENTS = '10046 trace name context forever'"
            ),
            "trailing EVENTS with a spacey/quoted value must be rejected"
        );
        assert!(
            !is_allowed_alter_session(
                "ALTER SESSION SET EDITION = app_release_v2 SQL_TRACE = TRUE"
            ),
            "EDITION must not smuggle SQL_TRACE past the complete allowlist check"
        );
        // The order does not matter: a non-allowlisted leading param also fails.
        assert!(!is_allowed_alter_session(
            "ALTER SESSION SET SQL_TRACE = TRUE CURRENT_SCHEMA = HR"
        ));
    }

    #[test]
    fn alter_session_permits_multiple_allowlisted_params() {
        // A genuinely-safe multi-param statement: every assignment is allowlisted.
        assert!(is_allowed_alter_session(
            "ALTER SESSION SET CURRENT_SCHEMA = HR OPTIMIZER_MODE = ALL_ROWS"
        ));
        assert!(is_allowed_alter_session(
            "ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD' NLS_LANGUAGE = AMERICAN"
        ));
    }

    #[test]
    fn alter_session_parser_advances_exactly_one_clause_per_iteration() {
        assert_eq!(
            alter_session_params(
                "CURRENT_SCHEMA = HR OPTIMIZER_MODE = ALL_ROWS NLS_LANGUAGE = AMERICAN"
            ),
            Some(vec![
                "CURRENT_SCHEMA".to_owned(),
                "OPTIMIZER_MODE".to_owned(),
                "NLS_LANGUAGE".to_owned(),
            ])
        );
    }

    #[test]
    fn alter_session_fails_closed_on_malformed() {
        // Zero assignments / no `=` → rejected.
        assert!(!is_allowed_alter_session(
            "ALTER SESSION SET CURRENT_SCHEMA"
        ));
        assert!(!is_allowed_alter_session("ALTER SESSION SET "));
        // Unterminated string literal → fail closed.
        assert!(!is_allowed_alter_session(
            "ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY"
        ));
        // A top-level `=` with no preceding parameter name → fail closed.
        assert!(!is_allowed_alter_session("ALTER SESSION SET = HR"));
        // A leading comment must not hide an ALTER SESSION whose full token
        // stream is malformed.
        assert!(!is_allowed_alter_session(
            "/* audit */ ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY"
        ));
    }

    #[test]
    fn alter_session_params_rejects_no_progress_tokenization() {
        assert_eq!(alter_session_params(" = HR"), None);
        assert_eq!(alter_session_params(" ="), None);
        assert_eq!(alter_session_params(" 'abc' = HR"), None);
    }

    #[test]
    fn alter_session_policy_distinguishes_non_statements_and_denied_forms() {
        assert_eq!(
            alter_session_policy("SELECT 'ALTER SESSION' FROM dual"),
            None
        );
        assert_eq!(alter_session_policy("ALTER TABLE session_log MOVE"), None);
        assert_eq!(
            alter_session_policy("-- ALTER SESSION SET SQL_TRACE=TRUE"),
            None
        );
        assert_eq!(
            alter_session_policy("ALTER SESSION SET EDITION = app_release_v2"),
            Some(true),
            "the narrow D1 widening is exactly the EDITION assignment"
        );

        for sql in [
            "ALTER SESSION SET SQL_TRACE = TRUE",
            "ALTER/**/SESSION SET CONTAINER = CDB$ROOT",
            "/* audit */ ALTER SESSION DISABLE GUARD",
            "ALTER SESSION ENABLE COMMIT IN PROCEDURE",
            "ALTER SESSION SET CURRENT_SCHEMA=HR/**/SQL_TRACE=TRUE",
            "ALTER SESSION SET EDITION = app_release_v2 SQL_TRACE = TRUE",
        ] {
            assert_eq!(
                alter_session_policy(sql),
                Some(false),
                "must recognize and deny {sql:?}"
            );
        }
    }

    #[test]
    fn alter_session_policy_rejects_empty_set_clause_as_forbidden() {
        assert_eq!(alter_session_policy("ALTER SESSION SET "), Some(false));
    }

    #[test]
    fn alter_session_allowlist_permits_quoted_values_with_reserved_chars() {
        assert!(is_allowed_alter_session(
            "ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY=MM' "
        ));
    }
}
